Dynamic Security Analysis Implementation
gridsuite/dynamic-security-analysis-server pull request #2
Opened 2024-11-18 20:57 UTC by thangqp

2025-02-05 09:48 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/DynamicSecurityAnalysisException.java
> +        DYNAMIC_SIMULATION_RESULT_UUID_NOT_FOUND,
since this every enum entry has a message why don't you change the enum to include the message

`        
DYNAMIC_SIMULATION_RESULT_UUID_NOT_FOUND("Dynamic simulation result not found"),
`


```
        Type(String msg) {
            message = msg;
        }
        private final String message;
        
        String getMessage() { // or you can override toString() if you wish
            return message;
        }
```

2025-02-05 11:36 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/dto/dynamicsimulation/DynamicSimulationParametersInfos.java
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
2025 ?

2025-02-05 11:36 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/dto/parameters/DynamicSecurityAnalysisParametersInfos.java
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
same 2025 ?

2025-02-05 11:37 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/entities/parameters/DynamicSecurityAnalysisParametersEntity.java
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
same here

2025-02-05 11:41 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/entities/parameters/DynamicSecurityAnalysisParametersEntity.java
> +    @Column(name = "id")
I think that column annotation is redundant here ! And same for the rest of the columns

2025-02-05 13:22 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/DynamicSecurityAnalysisObserver.java
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
2025

2025-02-05 15:17 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/entities/parameters/DynamicSecurityAnalysisParametersEntity.java
> +    @Column(name = "id")
In my opinion, using explicit mapping for all columns, entities is a good practice since it can enhance the readability of code, prevent accidental issues when refactoring. In addition, it is independent to whatever used dialect and make the code more homogeneous than using mapping case by case.

2025-02-05 15:42 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/dto/dynamicsimulation/DynamicSimulationParametersInfos.java
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
YES, some classes were created at the end of 2024, il will update all others classes

2025-02-05 15:42 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/dto/dynamicsimulation/DynamicSimulationParametersInfos.java
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
DONE in https://github.com/gridsuite/dynamic-security-analysis-server/pull/2/commits/4ab17ba9130d6ca0a6cc5c80e7da73aa53adbe68

2025-02-05 15:43 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/dto/parameters/DynamicSecurityAnalysisParametersInfos.java
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
DONE in https://github.com/gridsuite/dynamic-security-analysis-server/pull/2/commits/4ab17ba9130d6ca0a6cc5c80e7da73aa53adbe68

2025-02-05 15:43 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/entities/parameters/DynamicSecurityAnalysisParametersEntity.java
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
DONE in https://github.com/gridsuite/dynamic-security-analysis-server/pull/2/commits/4ab17ba9130d6ca0a6cc5c80e7da73aa53adbe68

2025-02-05 15:43 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/DynamicSecurityAnalysisObserver.java
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
DONE in https://github.com/gridsuite/dynamic-security-analysis-server/pull/2/commits/4ab17ba9130d6ca0a6cc5c80e7da73aa53adbe68

2025-02-05 15:48 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/DynamicSecurityAnalysisException.java
> +        DYNAMIC_SIMULATION_RESULT_UUID_NOT_FOUND,
It is the same as in others servers. Separating message from enum facilitates the customization of messages, for example, attach the id, name, etc..

2025-02-05 16:07 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/DynamicSecurityAnalysisException.java
> +        DYNAMIC_SIMULATION_RESULT_UUID_NOT_FOUND,
ok

2025-02-06 10:01 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/entities/DynamicSecurityAnalysisResultEntity.java
> +    @Column(name = "result_uuid")
you've change the name of the column in database, but i don't see any migration for that

2025-02-06 10:23 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/ParametersService.java
> +        if (providerToUse == null) {
why don't you concatenate this if with the one below you can do something like : 

```
        if (providerToUse == null) {
            providerToUse = runContext.getParameters().getProvider() != null ? runContext.getParameters().getProvider() : defaultProvider;
        }
```
or you can even use another approche : 

```
providerToUse = Optional.ofNullable(runContext)
        .map(RunContext::getParameters)
        .map(Parameters::getProvider)
        .orElse(defaultProvider);
```

2025-02-06 11:04 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/client/ActionsClient.java
> +    static final String API_VERSION = "v1";
is it on purpose that we define API_VERSION here and not in parent class ?

2025-02-06 12:33 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/client/utils/ExceptionUtils.java
> +    private ExceptionUtils() {
i Think you can use  annotation called @UtilityClass instead of that

2025-02-06 12:35 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/client/utils/ExceptionUtils.java
> +    private ExceptionUtils() {
here is what doc says about this annotation :

>  An annotation to create utility classes. If a class is annotated with @UtilityClass, the following things happen to it:
> It is marked final.
> If any constructors are declared in it, an error is generated. Otherwise, a private no-args constructor is generated; it throws a UnsupportedOperationException.
> All methods, inner classes, and fields in the class are marked static.
> WARNING: Do not use non-star static imports to import these members; javac won't be able to figure it out. Use either: import static ThisType.*; or don't static-import.

2025-02-06 12:37 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/client/utils/UrlUtils.java
> +    private UrlUtils() {
same here use @UtilityClass instead and remove constructor

2025-02-06 12:53 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/utils/Utils.java
> +public final class Utils {
use @UtilityClass annotation

2025-02-06 12:56 UTC, basseche commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/utils/Utils.java
> +    private Utils() {
remove constructor if you use UtilityClass annotation

2025-02-06 13:16 UTC, basseche commented on src/main/resources/db/changelog/changesets/changelog_20241219T225523Z.xml
maybe change the date of the file ? 2025... instead of 202412....

2025-02-06 13:29 UTC, basseche commented on src/test/java/org/gridsuite/dynamicsecurityanalysis/server/controller/utils/TestUtils.java
> +    private TestUtils() {
you can delete this constructor and use @UtilityClass annotation

2025-02-06 13:33 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/entities/DynamicSecurityAnalysisResultEntity.java
> +    @Column(name = "result_uuid")
mistake while copy/paste, I rectified it but no change in the generated liquibase change set

2025-02-06 13:42 UTC, basseche commented on src/test/resources/data/ieee14/IEEE14.iidm
I thought that we should not publish network data !

2025-02-06 13:46 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/ParametersService.java
> +        if (providerToUse == null) {
```suggestion
        if (providerToUse == null) {
            providerToUse = Optional.ofNullable(runContext.getParameters().getProvider()).orElse(defaultProvider);
        }
```
context, parameter always not null before this line, so I propose as above

2025-02-06 13:50 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/client/ActionsClient.java
> +    static final String API_VERSION = "v1";
Theoretically, each server can have different versions..

2025-02-06 13:53 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/client/utils/ExceptionUtils.java
> +    private ExceptionUtils() {
I don't know this annotation but its java doc says it is in an experimental package

2025-02-06 13:54 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/client/utils/UrlUtils.java
> +    private UrlUtils() {
Idem, it is an experimental annotation, not yet official

2025-02-06 13:54 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/utils/Utils.java
> +public final class Utils {
Idem, it is an experimental annotation, not yet official

2025-02-06 13:54 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/utils/Utils.java
> +    private Utils() {
Idem, it is an experimental annotation, not yet official

2025-02-06 13:59 UTC, thangqp commented on src/main/resources/db/changelog/changesets/changelog_20241219T225523Z.xml
Just a file name, only me who work on this sever, in addition no other changeset merged during my dev..

2025-02-06 13:59 UTC, thangqp commented on src/test/java/org/gridsuite/dynamicsecurityanalysis/server/controller/utils/TestUtils.java
> +    private TestUtils() {
experimental annotation

2025-02-06 14:01 UTC, thangqp commented on src/test/resources/data/ieee14/IEEE14.iidm
This is already published in powsybl-dynawo, it is a fake network which conforms to the public norm IEEE14

2025-02-06 15:43 UTC, etiennehomer requested changes

2025-02-06 15:43 UTC, etiennehomer commented on pom.xml
> +        <dependency>
Not required ?

2025-02-06 15:43 UTC, etiennehomer commented on pom.xml
> +        <dependency>
Not required ?

2025-02-06 16:05 UTC, thangqp commented on pom.xml
> +        <dependency>
DONE in https://github.com/gridsuite/dynamic-security-analysis-server/pull/2/commits/9e60ed175cc9f51760c247c534256fc2ee6268ba

2025-02-06 16:05 UTC, thangqp commented on pom.xml
> +        <dependency>
DONE in https://github.com/gridsuite/dynamic-security-analysis-server/pull/2/commits/9e60ed175cc9f51760c247c534256fc2ee6268ba

2025-02-07 08:33 UTC, etiennehomer commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/utils/Utils.java
> +    public static byte[] zip(InputStream is) throws IOException {
Move to test

2025-02-07 08:33 UTC, etiennehomer commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/utils/Utils.java
> +    public static <T> T unzip(byte[] zippedBytes, ObjectMapper objectMapper, TypeReference<T> valueTypeRef) throws IOException {
You need both methods ? Or even the 3 methods ?

2025-02-07 08:33 UTC, etiennehomer commented on src/test/java/org/gridsuite/dynamicsecurityanalysis/server/controller/DynamicSecurityAnalysisControllerIEEE14Test.java
> +            byte[] zippedOutputState = zip(outputStateIS);
You could have the file gzipped in the resources

2025-02-07 10:37 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/utils/Utils.java
> +    public static <T> T unzip(byte[] zippedBytes, ObjectMapper objectMapper, TypeReference<T> valueTypeRef) throws IOException {
Yes, to cover all cases of unzip whatever output data type

2025-02-07 10:42 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/utils/Utils.java
> +    public static byte[] zip(InputStream is) throws IOException {
In my opinion, move to a test utility class make the code difficult to maintain since we lost the symmetric to the unzipToStream method.

I think the best solution is extract all related zip/unzip methods into a separated class, i.e. GzipUtils

2025-02-07 11:46 UTC, thangqp commented on src/test/java/org/gridsuite/dynamicsecurityanalysis/server/controller/DynamicSecurityAnalysisControllerIEEE14Test.java
> +            byte[] zippedOutputState = zip(outputStateIS);
Theoretically, YES since it is in binary format, however others two files dynamicModel and parameters I need the original format json text to facilitate debug

DONE in https://github.com/gridsuite/dynamic-security-analysis-server/pull/2/commits/d158a8dd8ab8af9f5852bb450e2aee5effb47785

2025-02-10 08:49 UTC, etiennehomer commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/controller/DynamicSecurityAnalysisController.java
> +    @DeleteMapping(value = "/results", produces = APPLICATION_JSON_VALUE)
We have this endpoint for other computation servers. But it's dangerous and we don't use it I think

2025-02-10 12:11 UTC, etiennehomer commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/DynamicSecurityAnalysisWorkerService.java
> +                DynamicSecurityAnalysisStatus.FAILED :
You're sure of this rule ? One fail for one contingency => the computation is in failure ?

2025-02-10 12:41 UTC, etiennehomer commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/DynamicSecurityAnalysisWorkerService.java
> +                DynamicSecurityAnalysisStatus.FAILED :
It's the same in security-analysis-server ?

2025-02-10 16:17 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/controller/DynamicSecurityAnalysisController.java
> +    @DeleteMapping(value = "/results", produces = APPLICATION_JSON_VALUE)
whether we have some admin tool call to this endpoint? I see in LoadFlow server, we have an endpoint which accept a list of ids but also null list to delete all..

2025-02-10 16:21 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/DynamicSecurityAnalysisWorkerService.java
> +                DynamicSecurityAnalysisStatus.FAILED :
dynamic-security-analysis result is the same structure as normal SA but is interested in PostContingencyResult rather than PreContingencyResult...

2025-02-11 08:11 UTC, etiennehomer commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/utils/Utils.java
> +    public static byte[] zip(InputStream is) throws IOException {
Yes ok. It's already in Utils.java. It's enough I think. We could have it in powsybl-ws-commons

2025-02-11 08:16 UTC, etiennehomer commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/controller/DynamicSecurityAnalysisController.java
> +    @DeleteMapping(value = "/results", produces = APPLICATION_JSON_VALUE)
Ok yes, it's called by some admin tools scripts

2025-02-11 08:33 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/utils/Utils.java
> +    public static byte[] zip(InputStream is) throws IOException {
OK, we will move some methods immediately to ws-commons after merge these PRs..

2025-02-11 15:16 UTC, etiennehomer commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/DynamicSecurityAnalysisWorkerService.java
> +                        .withSeverity(postContingencyResult.getStatus() == PostContingencyComputationStatus.CONVERGED ? TypedValue.TRACE_SEVERITY : TypedValue.WARN_SEVERITY)
```suggestion
                        .withSeverity(postContingencyResult.getStatus() == PostContingencyComputationStatus.CONVERGED ? TypedValue.INFO_SEVERITY : TypedValue.ERROR_SEVERITY)
```

2025-02-11 15:50 UTC, thangqp commented on src/main/java/org/gridsuite/dynamicsecurityanalysis/server/service/DynamicSecurityAnalysisWorkerService.java
> +                        .withSeverity(postContingencyResult.getStatus() == PostContingencyComputationStatus.CONVERGED ? TypedValue.TRACE_SEVERITY : TypedValue.WARN_SEVERITY)
DONE in https://github.com/gridsuite/dynamic-security-analysis-server/pull/2/commits/86839d0bf9129471b99c42194e724a5f7c09a6c5

2025-02-11 15:51 UTC, thangqp commented on src/test/java/org/gridsuite/dynamicsecurityanalysis/server/controller/DynamicSecurityAnalysisControllerIEEE14Test.java
> +            byte[] zippedOutputState = zip(outputStateIS);
OK

2025-02-13 09:16 UTC, basseche approved these changes

2025-02-13 12:14 UTC, etiennehomer approved these changes

2025-02-13 12:16 UTC, etiennehomer approved these changes

2025-02-14 13:44 UTC, merged